# Generated by Django 5.1.2 on 2024-10-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_event_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.CharField(
                choices=[
                    ("work", "work"),
                    ("personal", "personal"),
                    ("health", "health"),
                ],
                max_length=50,
            ),
        ),
    ]
