# Generated by Django 5.1.2 on 2024-10-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_event_category"),
        ("user", "0002_remove_customuser_events_customuser_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="events",
            field=models.ManyToManyField(blank=True, to="events.event"),
        ),
    ]
